import type { RoleCode } from "./roles.seed";

export interface PermissionSeedDefinition {
  permissionId: string;
  permissionKey: string;
  resourceType: string;
  action: string;
  description: string;
  isSensitive: boolean;
  defaultRoles: readonly RoleCode[];
}

/**
 * Archivo generado desde docs/rules/MATRIZ-DE-PERMISOS.md v1.1.0.
 * No se interpreta Markdown durante db:seed.
 */
export const PERMISSION_DEFINITIONS = [
  {
    permissionId: "PERM-PUB-001",
    permissionKey: "public.landing.read",
    resourceType: "public.landing",
    action: "read",
    description: "Consultar landing y contenido institucional",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-PUB-002",
    permissionKey: "public.official-events.list",
    resourceType: "public.official-events",
    action: "list",
    description: "Listar eventos oficiales visibles",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-PUB-003",
    permissionKey: "public.official-events.read",
    resourceType: "public.official-events",
    action: "read",
    description: "Consultar detalle público de evento oficial",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-PUB-004",
    permissionKey: "public.results.list",
    resourceType: "public.results",
    action: "list",
    description: "Listar informes públicos",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-PUB-005",
    permissionKey: "public.results.read",
    resourceType: "public.results",
    action: "read",
    description: "Consultar resultado e informe público",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-PUB-006",
    permissionKey: "public.results.verify",
    resourceType: "public.results",
    action: "verify",
    description: "Consultar commitment, snapshot y verificación",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-PUB-007",
    permissionKey: "public.user-draws.list",
    resourceType: "public.user-draws",
    action: "list",
    description: "Listar sorteos de usuario públicos",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-PUB-008",
    permissionKey: "public.user-draws.read",
    resourceType: "public.user-draws",
    action: "read",
    description: "Consultar ficha pública de sorteo de usuario",
    isSensitive: false,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-AUTH-001",
    permissionKey: "auth.register",
    resourceType: "auth",
    action: "register",
    description: "Registrar una cuenta",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-AUTH-002",
    permissionKey: "auth.login",
    resourceType: "auth",
    action: "login",
    description: "Iniciar sesión",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-AUTH-003",
    permissionKey: "auth.refresh",
    resourceType: "auth",
    action: "refresh",
    description: "Rotar credencial de sesión",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-AUTH-004",
    permissionKey: "auth.logout",
    resourceType: "auth",
    action: "logout",
    description: "Cerrar sesión actual",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-AUTH-005",
    permissionKey: "auth.password-recovery",
    resourceType: "auth",
    action: "password-recovery",
    description: "Solicitar/restablecer contraseña",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SELF-001",
    permissionKey: "profile.self.read",
    resourceType: "profile.self",
    action: "read",
    description: "Consultar perfil propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-SELF-002",
    permissionKey: "profile.self.update",
    resourceType: "profile.self",
    action: "update",
    description: "Actualizar datos personales permitidos",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-SELF-003",
    permissionKey: "security.password.change",
    resourceType: "security.password",
    action: "change",
    description: "Cambiar contraseña propia",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-SELF-004",
    permissionKey: "sessions.self.list",
    resourceType: "sessions.self",
    action: "list",
    description: "Listar sesiones y dispositivos propios",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-SELF-005",
    permissionKey: "sessions.self.revoke",
    resourceType: "sessions.self",
    action: "revoke",
    description: "Revocar otra sesión propia",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-SELF-006",
    permissionKey: "sessions.mode.change",
    resourceType: "sessions.mode",
    action: "change",
    description: "Cambiar modo activo",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-SELF-007",
    permissionKey: "terms.self.accept",
    resourceType: "terms.self",
    action: "accept",
    description: "Aceptar versión de términos",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-SELF-008",
    permissionKey: "history.self.read",
    resourceType: "history.self",
    action: "read",
    description: "Consultar historial propio permitido",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-FIN-001",
    permissionKey: "wallet.self.read",
    resourceType: "wallet.self",
    action: "read",
    description: "Consultar wallets y componentes de saldo propios",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-FIN-002",
    permissionKey: "wallet.self.movements.read",
    resourceType: "wallet.self.movements",
    action: "read",
    description: "Consultar movimientos propios",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-FIN-003",
    permissionKey: "topup.self.create",
    resourceType: "topup.self",
    action: "create",
    description: "Crear recarga REAL simulada",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-FIN-004",
    permissionKey: "conversion.self.virtual-to-real",
    resourceType: "conversion.self",
    action: "virtual-to-real",
    description: "Convertir VIRTUAL a REAL",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-FIN-005",
    permissionKey: "withdrawal.self.create",
    resourceType: "withdrawal.self",
    action: "create",
    description: "Solicitar retiro REAL simulado",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-FIN-006",
    permissionKey: "withdrawal.self.read",
    resourceType: "withdrawal.self",
    action: "read",
    description: "Consultar retiros propios",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-FIN-007",
    permissionKey: "transfer.virtual.create",
    resourceType: "transfer.virtual",
    action: "create",
    description: "Transferir VIRTUAL",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-FIN-008",
    permissionKey: "conversion-request.client.create",
    resourceType: "conversion-request.client",
    action: "create",
    description: "Crear solicitud REAL→VIRTUAL",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-FIN-009",
    permissionKey: "conversion-request.client.read",
    resourceType: "conversion-request.client",
    action: "read",
    description: "Consultar solicitudes propias",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-FIN-010",
    permissionKey: "wallet.projection.repair",
    resourceType: "wallet.projection",
    action: "repair",
    description: "Reparar proyección desde ledger",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-VND-001",
    permissionKey: "vendor.dashboard.read",
    resourceType: "vendor.dashboard",
    action: "read",
    description: "Consultar resumen, capital, inventario y ganancias propias",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-VND-002",
    permissionKey: "vendor.inventory.read",
    resourceType: "vendor.inventory",
    action: "read",
    description: "Consultar inventario y lotes propios",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-VND-003",
    permissionKey: "vendor.inventory.purchase",
    resourceType: "vendor.inventory",
    action: "purchase",
    description: "Comprar VIRTUAL a 0,90 REAL por 1,00 VIRTUAL",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-VND-004",
    permissionKey: "vendor.requests.list",
    resourceType: "vendor.requests",
    action: "list",
    description: "Listar solicitudes compatibles",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-VND-005",
    permissionKey: "vendor.requests.assign",
    resourceType: "vendor.requests",
    action: "assign",
    description: "Tomar solicitud",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-VND-006",
    permissionKey: "vendor.requests.confirm",
    resourceType: "vendor.requests",
    action: "confirm",
    description: "Confirmar solicitud asignada",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-VND-007",
    permissionKey: "vendor.requests.cancel",
    resourceType: "vendor.requests",
    action: "cancel",
    description: "Cancelar/liberar asignación propia",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-VND-008",
    permissionKey: "vendor.sales.read",
    resourceType: "vendor.sales",
    action: "read",
    description: "Consultar ventas y ganancia realizada propias",
    isSensitive: true,
    defaultRoles: ["VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-OFF-001",
    permissionKey: "official.availability.read",
    resourceType: "official.availability",
    action: "read",
    description: "Consultar disponibilidad y combinaciones compatibles",
    isSensitive: false,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-002",
    permissionKey: "official.purchase-session.create",
    resourceType: "official.purchase-session",
    action: "create",
    description: "Crear sesión de compra oficial",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-003",
    permissionKey: "official.reservation.random",
    resourceType: "official.reservation",
    action: "random",
    description: "Reservar combinación aleatoria",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-004",
    permissionKey: "official.reservation.partial",
    resourceType: "official.reservation",
    action: "partial",
    description: "Reservar/completar selección parcial",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-005",
    permissionKey: "official.reservation.exact",
    resourceType: "official.reservation",
    action: "exact",
    description: "Reservar selección exacta",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-006",
    permissionKey: "official.cart.read",
    resourceType: "official.cart",
    action: "read",
    description: "Consultar carrito propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-007",
    permissionKey: "official.cart.release-item",
    resourceType: "official.cart",
    action: "release-item",
    description: "Liberar reserva propia del carrito",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-008",
    permissionKey: "official.purchase.confirm",
    resourceType: "official.purchase",
    action: "confirm",
    description: "Confirmar orden de compra",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-009",
    permissionKey: "official.tickets.list",
    resourceType: "official.tickets",
    action: "list",
    description: "Listar boletos propios",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-010",
    permissionKey: "official.tickets.read",
    resourceType: "official.tickets",
    action: "read",
    description: "Consultar boleto propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-011",
    permissionKey: "official.ticket.refund-request",
    resourceType: "official.ticket",
    action: "refund-request",
    description: "Solicitar revisión de cobro/error",
    isSensitive: true,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-OFF-012",
    permissionKey: "official.result.animation",
    resourceType: "official.result",
    action: "animation",
    description: "Reproducir/saltar animación",
    isSensitive: false,
    defaultRoles: ["CLIENTE"],
  },
  {
    permissionId: "PERM-ADM-001",
    permissionKey: "admin.users.read",
    resourceType: "admin.users",
    action: "read",
    description: "Consultar usuarios y perfiles administrativos",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-002",
    permissionKey: "admin.users.status.manage",
    resourceType: "admin.users.status",
    action: "manage",
    description: "Suspender, bloquear, activar o desactivar cuenta",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-003",
    permissionKey: "admin.users.roles.manage",
    resourceType: "admin.users.roles",
    action: "manage",
    description: "Asignar o retirar roles globales",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-004",
    permissionKey: "admin.permissions.read",
    resourceType: "admin.permissions",
    action: "read",
    description: "Consultar permisos y asignaciones",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-005",
    permissionKey: "admin.permissions.manage",
    resourceType: "admin.permissions",
    action: "manage",
    description: "Modificar asignaciones de permisos",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-006",
    permissionKey: "admin.rule-versions.read",
    resourceType: "admin.rule-versions",
    action: "read",
    description: "Consultar versiones de reglas",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-007",
    permissionKey: "admin.rule-versions.create",
    resourceType: "admin.rule-versions",
    action: "create",
    description: "Crear nueva versión de reglas",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-008",
    permissionKey: "admin.templates.read",
    resourceType: "admin.templates",
    action: "read",
    description: "Consultar plantillas/autogeneradores",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-009",
    permissionKey: "admin.templates.create",
    resourceType: "admin.templates",
    action: "create",
    description: "Crear plantilla/autogenerador",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-010",
    permissionKey: "admin.templates.update",
    resourceType: "admin.templates",
    action: "update",
    description: "Modificar plantilla futura",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-011",
    permissionKey: "admin.templates.activate",
    resourceType: "admin.templates",
    action: "activate",
    description: "Activar, pausar o retirar plantilla",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-012",
    permissionKey: "admin.events.read",
    resourceType: "admin.events",
    action: "read",
    description: "Consultar eventos y datos internos",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-013",
    permissionKey: "admin.events.create",
    resourceType: "admin.events",
    action: "create",
    description: "Crear evento oficial en borrador",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-014",
    permissionKey: "admin.events.publish",
    resourceType: "admin.events",
    action: "publish",
    description: "Publicar evento oficial",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-015",
    permissionKey: "admin.events.cancel",
    resourceType: "admin.events",
    action: "cancel",
    description: "Cancelar evento oficial",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-016",
    permissionKey: "admin.economy.simulate",
    resourceType: "admin.economy",
    action: "simulate",
    description: "Ejecutar simulador económico",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-017",
    permissionKey: "admin.funds.read",
    resourceType: "admin.funds",
    action: "read",
    description: "Consultar fondos y reservas",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-018",
    permissionKey: "admin.funds.contribute",
    resourceType: "admin.funds",
    action: "contribute",
    description: "Aportar al fondo de garantía",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-019",
    permissionKey: "admin.funds.future-prize.use",
    resourceType: "admin.funds.future-prize",
    action: "use",
    description: "Usar fondo de premios futuros",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-020",
    permissionKey: "admin.results.read",
    resourceType: "admin.results",
    action: "read",
    description: "Consultar commitments, snapshots, evaluación y estado interno",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-021",
    permissionKey: "admin.results.retry-process",
    resourceType: "admin.results",
    action: "retry-process",
    description: "Solicitar reintento de proceso de resultado/informe",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-022",
    permissionKey: "admin.reconciliation.run",
    resourceType: "admin.reconciliation",
    action: "run",
    description: "Solicitar reconciliación de ledger/fondos",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-023",
    permissionKey: "admin.audit.read",
    resourceType: "admin.audit",
    action: "read",
    description: "Consultar auditoría",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-024",
    permissionKey: "admin.audit.export",
    resourceType: "admin.audit",
    action: "export",
    description: "Exportar auditoría",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-025",
    permissionKey: "admin.security-events.read",
    resourceType: "admin.security-events",
    action: "read",
    description: "Consultar alertas de seguridad/riesgo",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-026",
    permissionKey: "admin.jobs.read",
    resourceType: "admin.jobs",
    action: "read",
    description: "Consultar trabajos y errores",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-027",
    permissionKey: "admin.jobs.retry",
    resourceType: "admin.jobs",
    action: "retry",
    description: "Reintentar trabajo agotado",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-028",
    permissionKey: "admin.settings.manage",
    resourceType: "admin.settings",
    action: "manage",
    description: "Gestionar configuración operativa no histórica",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ADM-029",
    permissionKey: "admin.platform-liquidity.fund",
    resourceType: "admin.platform-liquidity",
    action: "fund",
    description: "Fondear caja REAL o wallet general VIRTUAL",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-ORG-001",
    permissionKey: "user-draws.create",
    resourceType: "user-draws",
    action: "create",
    description: "Crear sorteo de usuario",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-002",
    permissionKey: "user-draws.own.read",
    resourceType: "user-draws.own",
    action: "read",
    description: "Consultar sorteo propio con datos internos",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-003",
    permissionKey: "user-draws.draft.update",
    resourceType: "user-draws.draft",
    action: "update",
    description: "Editar sorteo propio en borrador",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-004",
    permissionKey: "user-draws.publish",
    resourceType: "user-draws",
    action: "publish",
    description: "Publicar sorteo propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-005",
    permissionKey: "user-draws.range.expand",
    resourceType: "user-draws.range",
    action: "expand",
    description: "Ampliar rango",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-006",
    permissionKey: "user-draws.announcements.create",
    resourceType: "user-draws.announcements",
    action: "create",
    description: "Publicar anuncio interno",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-007",
    permissionKey: "user-draws.timeline.read",
    resourceType: "user-draws.timeline",
    action: "read",
    description: "Consultar historial completo del sorteo propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-008",
    permissionKey: "user-draws.cancel",
    resourceType: "user-draws",
    action: "cancel",
    description: "Cancelar sorteo propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-009",
    permissionKey: "user-draws.codes.issue",
    resourceType: "user-draws.codes",
    action: "issue",
    description: "Emitir código privado",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-010",
    permissionKey: "user-draws.codes.read",
    resourceType: "user-draws.codes",
    action: "read",
    description: "Consultar códigos propios e historial",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-011",
    permissionKey: "user-draws.code.claim",
    resourceType: "user-draws.code",
    action: "claim",
    description: "Reclamar código privado",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-012",
    permissionKey: "user-draws.participation.buy",
    resourceType: "user-draws.participation",
    action: "buy",
    description: "Comprar participación",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-013",
    permissionKey: "user-draws.participation.buy-additional",
    resourceType: "user-draws.participation",
    action: "buy-additional",
    description: "Comprar participación adicional",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-014",
    permissionKey: "user-draws.participation.change-number",
    resourceType: "user-draws.participation",
    action: "change-number",
    description: "Cambiar número propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-015",
    permissionKey: "user-draws.participation.abandon",
    resourceType: "user-draws.participation",
    action: "abandon",
    description: "Abandonar participación propia",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-016",
    permissionKey: "user-draws.announcements.read",
    resourceType: "user-draws.announcements",
    action: "read",
    description: "Consultar anuncios internos",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-017",
    permissionKey: "user-draws.participants.expel",
    resourceType: "user-draws.participants",
    action: "expel",
    description: "Expulsar participante",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-018",
    permissionKey: "user-draws.claim.create",
    resourceType: "user-draws.claim",
    action: "create",
    description: "Presentar reclamo",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-019",
    permissionKey: "user-draws.claim.read-own",
    resourceType: "user-draws.claim",
    action: "read-own",
    description: "Consultar reclamo propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-020",
    permissionKey: "user-draws.claim.respond",
    resourceType: "user-draws.claim",
    action: "respond",
    description: "Responder y aportar evidencia como Organizador",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-021",
    permissionKey: "user-draws.claim.appeal",
    resourceType: "user-draws.claim",
    action: "appeal",
    description: "Apelar resolución propia",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-022",
    permissionKey: "user-draws.delivery.register",
    resourceType: "user-draws.delivery",
    action: "register",
    description: "Registrar evidencia de entrega",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-023",
    permissionKey: "user-draws.delivery.confirm",
    resourceType: "user-draws.delivery",
    action: "confirm",
    description: "Confirmar recepción del premio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-024",
    permissionKey: "user-draws.delivery.dispute",
    resourceType: "user-draws.delivery",
    action: "dispute",
    description: "Abrir reclamo por entrega",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-ORG-025",
    permissionKey: "user-draws.escrow.read",
    resourceType: "user-draws.escrow",
    action: "read",
    description: "Consultar estado agregado del escrow propio",
    isSensitive: true,
    defaultRoles: ["CLIENTE", "VENDEDOR", "ADMINISTRADOR"],
  },
  {
    permissionId: "PERM-MOD-001",
    permissionKey: "admin.user-draws.read-all",
    resourceType: "admin.user-draws",
    action: "read-all",
    description: "Consultar sorteos de usuario y datos de moderación",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-002",
    permissionKey: "admin.user-draws.evidence.read",
    resourceType: "admin.user-draws.evidence",
    action: "read",
    description: "Consultar evidencia de premio/entrega",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-003",
    permissionKey: "admin.user-draws.claim.admit",
    resourceType: "admin.user-draws.claim",
    action: "admit",
    description: "Admitir reclamo",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-004",
    permissionKey: "admin.user-draws.claim.request-evidence",
    resourceType: "admin.user-draws.claim",
    action: "request-evidence",
    description: "Solicitar evidencia",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-005",
    permissionKey: "admin.user-draws.claim.resolve",
    resourceType: "admin.user-draws.claim",
    action: "resolve",
    description: "Resolver o rechazar reclamo",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-006",
    permissionKey: "admin.user-draws.claim.reopen",
    resourceType: "admin.user-draws.claim",
    action: "reopen",
    description: "Reabrir reclamo fuera de plazo",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-007",
    permissionKey: "admin.user-draws.claim.close",
    resourceType: "admin.user-draws.claim",
    action: "close",
    description: "Cerrar reclamo firme",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-008",
    permissionKey: "admin.user-draws.escrow.hold",
    resourceType: "admin.user-draws.escrow",
    action: "hold",
    description: "Mantener/bloquear escrow por disputa",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-009",
    permissionKey: "admin.user-draws.escrow.release",
    resourceType: "admin.user-draws.escrow",
    action: "release",
    description: "Autorizar liberación del 95 %",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-010",
    permissionKey: "admin.user-draws.refund.order",
    resourceType: "admin.user-draws.refund",
    action: "order",
    description: "Ordenar reembolso por incumplimiento",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-011",
    permissionKey: "admin.user-draws.breach.confirm",
    resourceType: "admin.user-draws.breach",
    action: "confirm",
    description: "Confirmar incumplimiento del Organizador",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-MOD-012",
    permissionKey: "admin.user-draws.post-close-measure",
    resourceType: "admin.user-draws",
    action: "post-close-measure",
    description: "Aplicar medida posterior al cierre mediante reclamo",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-001",
    permissionKey: "system.reservations.expire",
    resourceType: "system.reservations",
    action: "expire",
    description: "Expirar reservas oficiales",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-002",
    permissionKey: "system.conversion-request.fallback",
    resourceType: "system.conversion-request",
    action: "fallback",
    description: "Completar/fallar solicitud al minuto cinco",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-003",
    permissionKey: "system.events.open-sales",
    resourceType: "system.events",
    action: "open-sales",
    description: "Abrir ventas oficiales",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-004",
    permissionKey: "system.events.close-sales",
    resourceType: "system.events",
    action: "close-sales",
    description: "Cerrar ventas oficiales",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-005",
    permissionKey: "system.events.freeze",
    resourceType: "system.events",
    action: "freeze",
    description: "Congelar boletos y snapshot",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-006",
    permissionKey: "system.results.generate",
    resourceType: "system.results",
    action: "generate",
    description: "Generar resultado oficial",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-007",
    permissionKey: "system.tickets.evaluate",
    resourceType: "system.tickets",
    action: "evaluate",
    description: "Evaluar boletos",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-008",
    permissionKey: "system.reports.publish",
    resourceType: "system.reports",
    action: "publish",
    description: "Publicar informe oficial",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-009",
    permissionKey: "system.awards.credit",
    resourceType: "system.awards",
    action: "credit",
    description: "Acreditar premios/devoluciones",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-010",
    permissionKey: "system.refunds.execute",
    resourceType: "system.refunds",
    action: "execute",
    description: "Ejecutar reembolsos oficiales/de usuario",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-011",
    permissionKey: "system.funds.distribute",
    resourceType: "system.funds",
    action: "distribute",
    description: "Distribuir evento sin ganador",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-012",
    permissionKey: "system.user-draws.codes.expire",
    resourceType: "system.user-draws.codes",
    action: "expire",
    description: "Expirar códigos privados",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-013",
    permissionKey: "system.user-draws.freeze",
    resourceType: "system.user-draws",
    action: "freeze",
    description: "Congelar snapshot de participaciones",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-014",
    permissionKey: "system.user-draws.result.generate",
    resourceType: "system.user-draws.result",
    action: "generate",
    description: "Generar ganador de sorteo de usuario",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-015",
    permissionKey: "system.user-draws.escrow.settle",
    resourceType: "system.user-draws.escrow",
    action: "settle",
    description: "Ejecutar liberación/reembolso de escrow",
    isSensitive: true,
    defaultRoles: [],
  },
  {
    permissionId: "PERM-SYS-016",
    permissionKey: "system.ledger.reconcile",
    resourceType: "system.ledger",
    action: "reconcile",
    description: "Reconciliar ledger y proyecciones",
    isSensitive: true,
    defaultRoles: [],
  },
] as const satisfies readonly PermissionSeedDefinition[];

export const EXPECTED_PERMISSION_COUNT = 133;

export const EXPECTED_DEFAULT_ROLE_PERMISSION_COUNTS: Readonly<Record<RoleCode, number>> = {
  CLIENTE: 54,
  VENDEDOR: 47,
  ADMINISTRADOR: 47,
};

